name: Run tests

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: "Run tests"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.0
          - 2.7
          - 2.6
          - 2.5
        gemfile:
          - gemfiles/dogstatsd_ruby_4.gemfile
          - gemfiles/dogstatsd_ruby_5.gemfile
    container:
      image: ruby:${{ matrix.ruby }}
      env:
        CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile', '**/*.gemfile') }}
          restore-keys: |
            bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile', '**/*.gemfile') }}
            bundle-${{ matrix.ruby }}-
      - name: Upgrade Bundler to 2.0 (for older Rubies)
        run: gem install bundler -v '~> 2.0'
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --gemfile ${{ matrix.gemfile }}
          bundle update
      - name: Run RSpec
        run: bundle exec rspec
